version: "2.2"
services:
  surge:
    build: ./docker
    #image: ghcr.io/cheminfo/surge-docker:1.1.0
    restart: always
    ulimits:
      core: 0
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    ports:
      - 127.0.0.1:31228:31228
